version: '3'
services:
  postgres:
    image: pgvector/pgvector:0.7.2-pg15
    container_name: postgres_docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5420:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
